### ISSUE TITLE
Mapping decompiled assembly to source

### ISSUE THREAD

**Issue by yui-ishihara** [SoftSec-KAIST/BinKit#2]
Thank you for providing this comprehensive dataset. It is the best one I have found for binary code analysis!

I downloaded the dataset `sizeopt_dataset.7z` and tried to decompile some of the `.elf` files using `objdump -d <file>` command. It turns out many of these `.elf` could be successfully decompiled (some could not). For example, for `a2ps/a2ps-4.14_gcc-8.2.0_x86_32_Os_a2ps.elf`, I have something that looks like (with more than 50000 lines)

```asm
a2ps-4.14_gcc-8.2.0_x86_32_Os_a2ps.elf:     file format elf32-i386


Disassembly of section .init:

08049624 <_init>:
 8049624:	53                   	push   %ebx
 8049625:	83 ec 08             	sub    $0x8,%esp
 8049628:	e8 93 0c 00 00       	call   804a2c0 <__x86.get_pc_thunk.bx>
 804962d:	81 c3 d3 49 04 00    	add    $0x449d3,%ebx
 8049633:	8b 83 fc ff ff ff    	mov    -0x4(%ebx),%eax
 8049639:	85 c0                	test   %eax,%eax
 804963b:	74 05                	je     8049642 <_init+0x1e>
 804963d:	e8 fe 05 00 00       	call   8049c40 <__gmon_start__@plt>
 8049642:	e8 22 0d 00 00       	call   804a369 <frame_dummy>
 8049647:	e8 07 b8 02 00       	call   8074e53 <__do_global_ctors_aux>
 804964c:	83 c4 08             	add    $0x8,%esp
 804964f:	5b                   	pop    %ebx
 8049650:	c3                   	ret    

Disassembly of section .plt:

08049660 <.plt>:
 8049660:	ff 35 04 e0 08 08    	pushl  0x808e004
 8049666:	ff 25 08 e0 08 08    	jmp    *0x808e008
 804966c:	00 00                	add    %al,(%eax)
...
```

I am not quite familiar with hardware and low-levels. I am wondering if there is any possibility I could map each section of these assembly codes to the source I found for `a2ps`. 

```text
buffer.c    lexps.c         main.h           read.h        ssheet.h
buffer.h    lexps.h         Makefile.am      regex.c       sshread.c
delegate.c  lexps.l         Makefile.in      regex.h       sshread.h
delegate.h  lexssh.c        parsessh.c       select.c      version-etc.c
ffaces.c    lexssh.l        parsessh.h       select.h      version-etc.h
ffaces.h    long-options.c  parsessh.output  sheets-map.c  versions.c
generate.c  long-options.h  parsessh.y       sheets-map.l  versions.h
generate.h  main.c          read.c           ssheet.c      yy2ssh.h
```
Thank you. I am looking forward to your reply.
Cheers,

Yui

**Comment by 0xdkay** [comment]
Thanks for your interest in BinKit :)

You can map assembly instructions to the corresponding source file and line using the DWARF information in a ELF binary. Note that this information remains if the binary is compiled with the debug option, and the binaries in BinKit is compiled this way.

However, as you might already know, a single line of assembly code cannot be directly mapped to the line of source code because a single source code line can be compiled to multiple assembly instructions. Even some compilers insert their built-in assembly instructions, which do not exist in the original source code. 

Meanwhile, mapping such information would be very useful for understanding the relationship between the assembly code and source code, and I will consider adding this feature in the next version of [TikNib](https://github.com/SoftSec-KAIST/TikNib).

BTW, I would use the word "disassemble" in your example. The word "decompile" represents recovering semantics of assembly instructions, such that one can see the pseudo code or even the source code. You can check IDA Pro hex-rays or Ghidra, which are tools having decompilers. For basic knowledge of binary analysis, please check Section 2 of [our paper](https://arxiv.org/abs/2011.10749).

**Comment by 0xdkay** [comment]
Please check the above issue in [TikNib](https://github.com/SoftSec-KAIST/TikNib/issues/2)
