### ISSUE TITLE
Errors occurs when building gcc: isl download failed

### ISSUE THREAD

**Issue by xiaoguai0992** [SoftSec-KAIST/BinKit#4]
Hi, I am trying to build BinKit.

When I was execute "setup_gcc", some error occurs.

```
[00:10] / gmake: *** [/mnt/nfs/repo/BinKit/tools//crosstool-ng/ct-ng:261：build] error 1
/mnt/nfs/repo/BinKit//ctng_conf/5.5/mipseb_32
[ERROR]    isl: download failed
```

According to config file, CT_ISL_MIRRORS=http://isl.gforge.inria.fr/

However, this source seems down for a long period. [HERE](https://github.com/crosstool-ng/crosstool-ng/issues/769)

So is there any solutions? Thanks a lot.

**Comment by 0xdkay** [comment]
Hi, thanks for your interest.
I haven't seen this issue before. Could you let me know how to reproduce the error?

**Comment by marc-hb** [comment]
See https://github.com/crosstool-ng/crosstool-ng/issues/769

**Comment by bangin20** [comment]
I found another mirror site https://gcc.gnu.org/pub/gcc/infrastructure/ instead of http://isl.gforge.inria.fr/.

You can change all the config files in the ctng_conf/*

`sed -i 's#http://isl.gforge.inria.fr/#https://gcc.gnu.org/pub/gcc/infrastructure/#g' ctng_conf/*/*.conf do the job !

You can try with this new mirror site

**Comment by 0xdkay** [comment]
@marc-hb @bangin20 Thanks for your comments! I will check them!

**Comment by 0xdkay** [comment]
Thanks @bangin20 !
Simply changing the mirror URL addressed the problem. (16a8cee)
